/* eslint-disable simple-import-sort/imports */
// This file is auto-generated by scripts/precacheLibSources.mjs, do not manually edit it
import lib from "./parsed/lib.js"
import lib_decorators from "./parsed/lib.decorators.js"
import lib_decorators_legacy from "./parsed/lib.decorators.legacy.js"
import lib_dom_asynciterable from "./parsed/lib.dom.asynciterable.js"
import lib_dom from "./parsed/lib.dom.js"
import lib_dom_iterable from "./parsed/lib.dom.iterable.js"
import lib_es2015_collection from "./parsed/lib.es2015.collection.js"
import lib_es2015_core from "./parsed/lib.es2015.core.js"
import lib_es2015 from "./parsed/lib.es2015.js"
import lib_es2015_generator from "./parsed/lib.es2015.generator.js"
import lib_es2015_iterable from "./parsed/lib.es2015.iterable.js"
import lib_es2015_promise from "./parsed/lib.es2015.promise.js"
import lib_es2015_proxy from "./parsed/lib.es2015.proxy.js"
import lib_es2015_reflect from "./parsed/lib.es2015.reflect.js"
import lib_es2015_symbol from "./parsed/lib.es2015.symbol.js"
import lib_es2015_symbol_wellknown from "./parsed/lib.es2015.symbol.wellknown.js"
import lib_es2016_array_include from "./parsed/lib.es2016.array.include.js"
import lib_es2016 from "./parsed/lib.es2016.js"
import lib_es2016_full from "./parsed/lib.es2016.full.js"
import lib_es2016_intl from "./parsed/lib.es2016.intl.js"
import lib_es2017 from "./parsed/lib.es2017.js"
import lib_es2017_date from "./parsed/lib.es2017.date.js"
import lib_es2017_full from "./parsed/lib.es2017.full.js"
import lib_es2017_intl from "./parsed/lib.es2017.intl.js"
import lib_es2017_object from "./parsed/lib.es2017.object.js"
import lib_es2017_sharedmemory from "./parsed/lib.es2017.sharedmemory.js"
import lib_es2017_string from "./parsed/lib.es2017.string.js"
import lib_es2017_typedarrays from "./parsed/lib.es2017.typedarrays.js"
import lib_es2018_asyncgenerator from "./parsed/lib.es2018.asyncgenerator.js"
import lib_es2018_asynciterable from "./parsed/lib.es2018.asynciterable.js"
import lib_es2018 from "./parsed/lib.es2018.js"
import lib_es2018_full from "./parsed/lib.es2018.full.js"
import lib_es2018_intl from "./parsed/lib.es2018.intl.js"
import lib_es2018_promise from "./parsed/lib.es2018.promise.js"
import lib_es2018_regexp from "./parsed/lib.es2018.regexp.js"
import lib_es2019_array from "./parsed/lib.es2019.array.js"
import lib_es2019 from "./parsed/lib.es2019.js"
import lib_es2019_full from "./parsed/lib.es2019.full.js"
import lib_es2019_intl from "./parsed/lib.es2019.intl.js"
import lib_es2019_object from "./parsed/lib.es2019.object.js"
import lib_es2019_string from "./parsed/lib.es2019.string.js"
import lib_es2019_symbol from "./parsed/lib.es2019.symbol.js"
import lib_es2020_bigint from "./parsed/lib.es2020.bigint.js"
import lib_es2020 from "./parsed/lib.es2020.js"
import lib_es2020_date from "./parsed/lib.es2020.date.js"
import lib_es2020_full from "./parsed/lib.es2020.full.js"
import lib_es2020_intl from "./parsed/lib.es2020.intl.js"
import lib_es2020_number from "./parsed/lib.es2020.number.js"
import lib_es2020_promise from "./parsed/lib.es2020.promise.js"
import lib_es2020_sharedmemory from "./parsed/lib.es2020.sharedmemory.js"
import lib_es2020_string from "./parsed/lib.es2020.string.js"
import lib_es2020_symbol_wellknown from "./parsed/lib.es2020.symbol.wellknown.js"
import lib_es2021 from "./parsed/lib.es2021.js"
import lib_es2021_full from "./parsed/lib.es2021.full.js"
import lib_es2021_intl from "./parsed/lib.es2021.intl.js"
import lib_es2021_promise from "./parsed/lib.es2021.promise.js"
import lib_es2021_string from "./parsed/lib.es2021.string.js"
import lib_es2021_weakref from "./parsed/lib.es2021.weakref.js"
import lib_es2022_array from "./parsed/lib.es2022.array.js"
import lib_es2022 from "./parsed/lib.es2022.js"
import lib_es2022_error from "./parsed/lib.es2022.error.js"
import lib_es2022_full from "./parsed/lib.es2022.full.js"
import lib_es2022_intl from "./parsed/lib.es2022.intl.js"
import lib_es2022_object from "./parsed/lib.es2022.object.js"
import lib_es2022_regexp from "./parsed/lib.es2022.regexp.js"
import lib_es2022_sharedmemory from "./parsed/lib.es2022.sharedmemory.js"
import lib_es2022_string from "./parsed/lib.es2022.string.js"
import lib_es2023_array from "./parsed/lib.es2023.array.js"
import lib_es2023_collection from "./parsed/lib.es2023.collection.js"
import lib_es2023 from "./parsed/lib.es2023.js"
import lib_es2023_full from "./parsed/lib.es2023.full.js"
import lib_es5 from "./parsed/lib.es5.js"
import lib_es6 from "./parsed/lib.es6.js"
import lib_esnext_collection from "./parsed/lib.esnext.collection.js"
import lib_esnext from "./parsed/lib.esnext.js"
import lib_esnext_decorators from "./parsed/lib.esnext.decorators.js"
import lib_esnext_disposable from "./parsed/lib.esnext.disposable.js"
import lib_esnext_full from "./parsed/lib.esnext.full.js"
import lib_esnext_intl from "./parsed/lib.esnext.intl.js"
import lib_esnext_object from "./parsed/lib.esnext.object.js"
import lib_esnext_promise from "./parsed/lib.esnext.promise.js"
import lib_scripthost from "./parsed/lib.scripthost.js"
import lib_webworker_asynciterable from "./parsed/lib.webworker.asynciterable.js"
import lib_webworker from "./parsed/lib.webworker.js"
import lib_webworker_importscripts from "./parsed/lib.webworker.importscripts.js"
import lib_webworker_iterable from "./parsed/lib.webworker.iterable.js"

const mapping: Record<string, () => object> = {
    "lib.d.ts": lib,
    "lib.decorators.d.ts": lib_decorators,
    "lib.decorators.legacy.d.ts": lib_decorators_legacy,
    "lib.dom.asynciterable.d.ts": lib_dom_asynciterable,
    "lib.dom.d.ts": lib_dom,
    "lib.dom.iterable.d.ts": lib_dom_iterable,
    "lib.es2015.collection.d.ts": lib_es2015_collection,
    "lib.es2015.core.d.ts": lib_es2015_core,
    "lib.es2015.d.ts": lib_es2015,
    "lib.es2015.generator.d.ts": lib_es2015_generator,
    "lib.es2015.iterable.d.ts": lib_es2015_iterable,
    "lib.es2015.promise.d.ts": lib_es2015_promise,
    "lib.es2015.proxy.d.ts": lib_es2015_proxy,
    "lib.es2015.reflect.d.ts": lib_es2015_reflect,
    "lib.es2015.symbol.d.ts": lib_es2015_symbol,
    "lib.es2015.symbol.wellknown.d.ts": lib_es2015_symbol_wellknown,
    "lib.es2016.array.include.d.ts": lib_es2016_array_include,
    "lib.es2016.d.ts": lib_es2016,
    "lib.es2016.full.d.ts": lib_es2016_full,
    "lib.es2016.intl.d.ts": lib_es2016_intl,
    "lib.es2017.d.ts": lib_es2017,
    "lib.es2017.date.d.ts": lib_es2017_date,
    "lib.es2017.full.d.ts": lib_es2017_full,
    "lib.es2017.intl.d.ts": lib_es2017_intl,
    "lib.es2017.object.d.ts": lib_es2017_object,
    "lib.es2017.sharedmemory.d.ts": lib_es2017_sharedmemory,
    "lib.es2017.string.d.ts": lib_es2017_string,
    "lib.es2017.typedarrays.d.ts": lib_es2017_typedarrays,
    "lib.es2018.asyncgenerator.d.ts": lib_es2018_asyncgenerator,
    "lib.es2018.asynciterable.d.ts": lib_es2018_asynciterable,
    "lib.es2018.d.ts": lib_es2018,
    "lib.es2018.full.d.ts": lib_es2018_full,
    "lib.es2018.intl.d.ts": lib_es2018_intl,
    "lib.es2018.promise.d.ts": lib_es2018_promise,
    "lib.es2018.regexp.d.ts": lib_es2018_regexp,
    "lib.es2019.array.d.ts": lib_es2019_array,
    "lib.es2019.d.ts": lib_es2019,
    "lib.es2019.full.d.ts": lib_es2019_full,
    "lib.es2019.intl.d.ts": lib_es2019_intl,
    "lib.es2019.object.d.ts": lib_es2019_object,
    "lib.es2019.string.d.ts": lib_es2019_string,
    "lib.es2019.symbol.d.ts": lib_es2019_symbol,
    "lib.es2020.bigint.d.ts": lib_es2020_bigint,
    "lib.es2020.d.ts": lib_es2020,
    "lib.es2020.date.d.ts": lib_es2020_date,
    "lib.es2020.full.d.ts": lib_es2020_full,
    "lib.es2020.intl.d.ts": lib_es2020_intl,
    "lib.es2020.number.d.ts": lib_es2020_number,
    "lib.es2020.promise.d.ts": lib_es2020_promise,
    "lib.es2020.sharedmemory.d.ts": lib_es2020_sharedmemory,
    "lib.es2020.string.d.ts": lib_es2020_string,
    "lib.es2020.symbol.wellknown.d.ts": lib_es2020_symbol_wellknown,
    "lib.es2021.d.ts": lib_es2021,
    "lib.es2021.full.d.ts": lib_es2021_full,
    "lib.es2021.intl.d.ts": lib_es2021_intl,
    "lib.es2021.promise.d.ts": lib_es2021_promise,
    "lib.es2021.string.d.ts": lib_es2021_string,
    "lib.es2021.weakref.d.ts": lib_es2021_weakref,
    "lib.es2022.array.d.ts": lib_es2022_array,
    "lib.es2022.d.ts": lib_es2022,
    "lib.es2022.error.d.ts": lib_es2022_error,
    "lib.es2022.full.d.ts": lib_es2022_full,
    "lib.es2022.intl.d.ts": lib_es2022_intl,
    "lib.es2022.object.d.ts": lib_es2022_object,
    "lib.es2022.regexp.d.ts": lib_es2022_regexp,
    "lib.es2022.sharedmemory.d.ts": lib_es2022_sharedmemory,
    "lib.es2022.string.d.ts": lib_es2022_string,
    "lib.es2023.array.d.ts": lib_es2023_array,
    "lib.es2023.collection.d.ts": lib_es2023_collection,
    "lib.es2023.d.ts": lib_es2023,
    "lib.es2023.full.d.ts": lib_es2023_full,
    "lib.es5.d.ts": lib_es5,
    "lib.es6.d.ts": lib_es6,
    "lib.esnext.collection.d.ts": lib_esnext_collection,
    "lib.esnext.d.ts": lib_esnext,
    "lib.esnext.decorators.d.ts": lib_esnext_decorators,
    "lib.esnext.disposable.d.ts": lib_esnext_disposable,
    "lib.esnext.full.d.ts": lib_esnext_full,
    "lib.esnext.intl.d.ts": lib_esnext_intl,
    "lib.esnext.object.d.ts": lib_esnext_object,
    "lib.esnext.promise.d.ts": lib_esnext_promise,
    "lib.scripthost.d.ts": lib_scripthost,
    "lib.webworker.asynciterable.d.ts": lib_webworker_asynciterable,
    "lib.webworker.d.ts": lib_webworker,
    "lib.webworker.importscripts.d.ts": lib_webworker_importscripts,
    "lib.webworker.iterable.d.ts": lib_webworker_iterable
};

/**
 * @param fileName Lib file name to lookup
 * @returns A new source file with unbound parent pointers for the given lib, if it exists
 */
export function getCachedLibSourceFile(fileName: string): object | undefined {
    return mapping[fileName]?.();
}