import fs from "fs";
import path from "path";

import ts from "../built/local/typescript.js";

async function main() {
    if (process.argv.length > 2) {
        console.log("Usage:");
        console.log("\tnode ./scripts/precacheLibSources.mjs");
        // TODO: disentangle lib building from source building
        console.log("\tnote: This copies the built lib back into src as pre-parsed source, so you should need to hereby local -> run this -> hereby local -> LKG");
        return;
    }

    const buildDir = "./built/local";
    const warning = `// This file is auto-generated by scripts/precacheLibSources.mjs, do not manually edit it`

    const names = fs.readdirSync(buildDir).filter(n => n.startsWith("lib.") && n.endsWith(".d.ts"));

    for (const lib of names) {
        const libContent = ts.sys.readFile(path.join(buildDir, lib));
        if (!libContent) {
            throw new Error(`Lib file ${lib} file contents not found.`);
        }
        const parsed = ts.createSourceFile(lib, libContent, {
            languageVersion: ts.ScriptTarget.ESNext,
            impliedNodeFormat: undefined,
            jsDocParsingMode: ts.JSDocParsingMode.ParseAll,
            setExternalModuleIndicator: _ => void 0,
        }, /*setParentNodes*/ false, ts.ScriptKind.TS);

        // eslint-disable-next-line no-null/no-null
        const objText = JSON.stringify(parsed);

        ts.sys.writeFile(`./src/lib-cache/parsed/${lib.replace(".d.ts", ".ts")}`,
`/* eslint-disable no-template-curly-in-string */
${warning}
export default function(): object {
    // @ts-ignore expression produces a union type that is too complex to represent
    return ${objText};
}
`);

    }

    ts.sys.writeFile(`./src/lib-cache/index.ts`,
`/* eslint-disable simple-import-sort/imports */
${warning}
${names.map(n => `import ${n.replace(".d.ts", "").replace(/\./g, "_")} from "./parsed/${n.replace(".d.ts", "")}.js"`).join("\n")}

const mapping: Record<string, () => object> = {
    ${names.map(n => `"${n}": ${n.replace(".d.ts", "").replace(/\./g, "_")}`).join(",\n    ")}
};

/**
 * @param fileName Lib file name to lookup
 * @returns A new source file with unbound parent pointers for the given lib, if it exists
 */
export function getCachedLibSourceFile(fileName: string): object | undefined {
    return mapping[fileName]?.();
}`);
}

main();